bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: lcFgpkbox/vxgWyUgh2msqyiUb0IpDoD39kqYIj/SVisPCuzDr/DExqsIeozRQRDF/NtairRzSr45dzdp8okAfH4DV+r9v3yXNLg06HIJVLuyyaJ0c6al/5QuMhWaL/9nCspAbwmXN2PSmNoX0al+dBII7z7esjUPZxZv25xYkBA8I7xasdLnuoC8qlUtuzUfEYyl1SlLsyxXBfwxqIRtayzxr53KMQKdCW0n+/bP2UOGIrtAw9At/CIn3dWrrq72In2DxHV7siRBapUaW2HekLlM1cw+0uzGGZu13YzIRTzusFJZ/ISTbXFDd41sFilMc/ktVBUzMrNxXnnUrBiRRhiCS8TRIvzjst/fgBgebdVvderxsrT906GnQxwYBMp8xWiUxbqoGeUIp6IKr9P311AlEaX0icAG/M8UQ4A5L8LEQPBtpsmed8zQYJwotaN+vS2WWa6XTYVkNznFt2bY7yb+h1il+OcNQbB5cj0qJhvRPiklgPCMdhoHTdCjdak1Ain5n1Fjr5bBV2nWjMG6hBn1Q1sN6MFCMKVs7e75isCj3zU31HsyZHPWQdeyKpvOmHqQgdKu3kSqmvhFCdoX/zhmIqDoxL8nLBzy6WFTbPxqm731qSatU2CoZnFYoADAhWbHmIb4G3NMLcv+4dT+idgbPmPvZnTc0xp03vD2rg=
conda_forge_output_validation: true
